"""Constants for Emmeti Mirai integration."""

DOMAIN = "emmeti_mirai"
DEFAULT_NAME = "Emmeti Mirai"
DEFAULT_PORT = 502
DEFAULT_SLAVE_ID = 1
DEFAULT_SCAN_INTERVAL = 30

CONF_HOST = "host"
CONF_PORT = "port"
CONF_SLAVE_ID = "slave_id"
CONF_SCAN_INTERVAL = "scan_interval"

# ---------------------------------------------------------------------------
# Modbus Register Map – Emmeti Mirai (tutti holding, slave 1)
# Fonte: modbus.yaml installazione reale
# ---------------------------------------------------------------------------
MODBUS_REGISTERS = [

    # ── Misure live ─────────────────────────────────────────────────────────
    {
        "key": "t_esterna",
        "name": "Temperatura esterna",
        "register": 8985,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "t_acqua_uscita",
        "name": "Temperatura acqua uscita",
        "register": 8986,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "t_acqua_entrata",
        "name": "Temperatura acqua entrata",
        "register": 8987,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "t_acs_raw",
        "name": "Temperatura ACS",
        "register": 8988,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "t_ambiente_raw",
        "name": "Temperatura ambiente interno",
        "register": 8992,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "umidita_ambiente",
        "name": "Umidità ambiente",
        "register": 8993,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "%", "device_class": "humidity",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "dewpoint_ambiente",
        "name": "Dewpoint ambiente interno",
        "register": 8994,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "circolatore",
        "name": "Circolatore PDC",
        "register": 9006,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "step_frequenza",
        "name": "Step frequenza richiesto",
        "register": 9007,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "portata_acqua",
        "name": "Portata acqua",
        "register": 9016,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": "L", "device_class": "water",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "consumo_pdc",
        "name": "Consumo elettrico PDC",
        "register": 9017,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": "W", "device_class": "power",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "potenza_termica_riscaldamento",
        "name": "Potenza termica riscaldamento",
        "register": 9019,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": "W", "device_class": "power",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "potenza_termica_raffrescamento",
        "name": "Potenza termica raffrescamento",
        "register": 9021,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": "W", "device_class": "power",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "cop",
        "name": "COP",
        "register": 9023,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "consumo_hotwater",
        "name": "Consumo Hot Water ACS",
        "register": 9035,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": "W", "device_class": "power",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "ore_compressore",
        "name": "Ore lavoro compressore",
        "register": 9033,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": "h", "device_class": None,
        "state_class": "total_increasing",
        "entity_type": "sensor", "writable": False,
    },

    # ── Ingressi digitali ────────────────────────────────────────────────────
    {
        "key": "ingresso_100",
        "name": "Ingresso digitale 100 (C+ C-)",
        "register": 8970,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "ingresso_101",
        "name": "Ingresso digitale 101 (D+ D-)",
        "register": 8971,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "ingresso_102",
        "name": "Ingresso digitale 102 (E+ E-)",
        "register": 8972,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "ingresso_103",
        "name": "Ingresso digitale 103 (F+ F-)",
        "register": 8973,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "ingresso_104",
        "name": "Ingresso digitale 104 (G+ G-)",
        "register": 8974,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "ingresso_105",
        "name": "Ingresso digitale 105 (H+ H-)",
        "register": 8975,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "crono_th_abilitazione",
        "name": "Stato abilitazione CRONO-TH",
        "register": 8983,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },

    # ── Uscite digitali ──────────────────────────────────────────────────────
    {
        "key": "uscita_200",
        "name": "Uscita 200 - Consenso riscaldatore ACS",
        "register": 8999,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "uscita_201",
        "name": "Uscita 201 - Consenso CRONO-TH",
        "register": 9000,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "uscita_202",
        "name": "Uscita 202 - Consenso Eco Hot Water",
        "register": 9001,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "uscita_203",
        "name": "Uscita 203 - Consenso generatore secondario",
        "register": 9002,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "uscita_204",
        "name": "Uscita 204 - Consenso valvola 3-vie ACS",
        "register": 9003,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "uscita_205",
        "name": "Uscita 205 - Consenso deumidificatore",
        "register": 9004,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },

    # ── Allarmi ──────────────────────────────────────────────────────────────
    {
        "key": "al00_sonda_esterna",
        "name": "Allarme - Sonda temperatura esterna",
        "register": 9094,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al01_sonda_acqua_entrata",
        "name": "Allarme - Sonda acqua entrata",
        "register": 9095,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al02_sonda_acqua_uscita",
        "name": "Allarme - Sonda acqua uscita",
        "register": 9096,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al03_termostato",
        "name": "Allarme - Termostato",
        "register": 9097,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al04_generico",
        "name": "Allarme - Errore generico",
        "register": 9098,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al05_sonda_ambiente",
        "name": "Allarme - Sonda temperatura ambiente",
        "register": 9099,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al06_sonda_umidita",
        "name": "Allarme - Sonda umidità ambiente",
        "register": 9100,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al07_condensa",
        "name": "Allarme - Condensa impianto radiante",
        "register": 9101,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al08_surriscaldamento",
        "name": "Allarme - Surriscaldamento impianto radiante",
        "register": 9102,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "al09_bassa_portata",
        "name": "Allarme - Bassa portata",
        "register": 9103,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },

    # ── Storico allarmi ──────────────────────────────────────────────────────
    {
        "key": "storico_allarme_codice",
        "name": "Codice allarme storico",
        "register": 9107,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "storico_allarme_data",
        "name": "Data allarme storico (gg.mm)",
        "register": 9108,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "storico_allarme_ora",
        "name": "Ora allarme storico (hh:mm)",
        "register": 9109,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },

    # ── Termoregolazione massetto (set di lavoro live) ───────────────────────
    {
        "key": "l500_set_temp_ambiente",
        "name": "Set lavoro temperatura ambiente (CRONO-TH)",
        "register": 9084,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "l501_set_temp_ritorno",
        "name": "Set lavoro temperatura ritorno massetto",
        "register": 9085,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "l502_freq_max_compressore",
        "name": "Set lavoro frequenza massima compressore",
        "register": 9089,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 1, "offset": 0,
        "unit": None, "device_class": None,
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "l550_target_acqua_modulazione",
        "name": "Target temperatura acqua modulazione",
        "register": 9086,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "l551_temp_acqua_modulazione",
        "name": "Temperatura acqua attuale modulazione",
        "register": 9079,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "l559_correzione_acqua",
        "name": "Correzione temperatura acqua massetto",
        "register": 9082,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "l562_temp_min_acqua_fredda",
        "name": "Temperatura minima acqua fredda impianto",
        "register": 9083,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": "measurement",
        "entity_type": "sensor", "writable": False,
    },

    # ── Offset sonde (read-only per monitoraggio) ────────────────────────────
    {
        "key": "offset_acqua_uscita",
        "name": "Offset sonda acqua uscita",
        "register": 8996,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },
    {
        "key": "offset_acqua_entrata",
        "name": "Offset sonda acqua entrata",
        "register": 8997,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "sensor", "writable": False,
    },

    # ── Setpoint scrivibili (number) ─────────────────────────────────────────
    {
        "key": "setpoint_comfort",
        "name": "Setpoint temperatura comfort",
        "register": 16439,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 15.0, "max_value": 30.0, "step": 0.5,
    },
    {
        "key": "setpoint_heat_p1",
        "name": "Heat P1 - Temperatura",
        "register": 16443,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 20.0, "max_value": 60.0, "step": 0.5,
    },
    {
        "key": "setpoint_heat_p2",
        "name": "Heat P2 - Temperatura",
        "register": 16445,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 20.0, "max_value": 60.0, "step": 0.5,
    },
    {
        "key": "setpoint_heat_p3",
        "name": "Heat P3 - Temperatura",
        "register": 16447,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 20.0, "max_value": 60.0, "step": 0.5,
    },
    {
        "key": "setpoint_heat_p4",
        "name": "Heat P4 - Temperatura",
        "register": 16449,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 20.0, "max_value": 60.0, "step": 0.5,
    },
    {
        "key": "setpoint_cool_p1",
        "name": "Cool P1 - Temperatura",
        "register": 16450,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 7.0, "max_value": 25.0, "step": 0.5,
    },
    {
        "key": "setpoint_cool_p2",
        "name": "Cool P2 - Temperatura",
        "register": 16452,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 7.0, "max_value": 25.0, "step": 0.5,
    },
    {
        "key": "setpoint_cool_p3",
        "name": "Cool P3 - Temperatura",
        "register": 16454,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 7.0, "max_value": 25.0, "step": 0.5,
    },
    {
        "key": "setpoint_cool_p4",
        "name": "Cool P4 - Temperatura",
        "register": 16456,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 7.0, "max_value": 25.0, "step": 0.5,
    },
    {
        "key": "acs_mantenimento",
        "name": "ACS - Temperatura mantenimento",
        "register": 16496,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 40.0, "max_value": 70.0, "step": 0.5,
    },
    {
        "key": "acs_temp1",
        "name": "ACS - Temperatura fascia 1",
        "register": 16493,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 40.0, "max_value": 70.0, "step": 0.5,
    },
    {
        "key": "acs_temp2",
        "name": "ACS - Temperatura fascia 2",
        "register": 16495,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 40.0, "max_value": 70.0, "step": 0.5,
    },
    {
        "key": "pot_max_limitazione",
        "name": "Potenza max limitazione",
        "register": 16479,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "kW", "device_class": "power",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 0.0, "max_value": 20.0, "step": 0.1,
    },
    {
        "key": "c803_diff_setpoint_powerboost",
        "name": "Differenziale SetPoint PowerBoost",
        "register": 16516,
        "register_type": "holding",
        "data_type": "int16",
        "scale": 0.1, "offset": 0,
        "unit": "°C", "device_class": "temperature",
        "state_class": None,
        "entity_type": "number", "writable": True,
        "min_value": 0.0, "max_value": 10.0, "step": 0.5,
    },
]

# Indice per entity_type
REGISTERS_BY_ENTITY_TYPE: dict = {}
for _reg in MODBUS_REGISTERS:
    REGISTERS_BY_ENTITY_TYPE.setdefault(_reg["entity_type"], []).append(_reg)
